version: '3.8'
services:
  babyagi-agent:
    build: .
    ports:
      - "5000:5000"
      - "7860:7860"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LLM_PROVIDER=openai
      - LOG_LEVEL=INFO
    volumes:
      - ./chroma_db:/app/chroma_db
    depends_on:
      - chroma-db

  chroma-db:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - IS_PERSISTENT=TRUE
    volumes:
      - ./chroma_data:/chroma/chroma_data